version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Australia/Brisbane"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions-non-breaking:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: "Australia/Brisbane"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python
    groups:
      python-non-breaking:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
